apiVersion: v1
kind: ConfigMap
metadata:
  name: appname
data:
  application.yml: |-
                    server:
                      port: 8080
                    management:
                      endpoints:
                        web:
                          exposure:
                            include: "*"
                      endpoint:
                        health:
                          probes: 
                            enabled: true
                        metrics:
                          enabled: false
                        prometheus:
                          enabled: true
                    app:
                      name: teste k8s
 
