apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: callout
              image: buildpack-deps:curl
              args:
                - /bin/sh
                - -ec
                - curl http://myapp.dev.svc.cluster.local:8080/api/v1/persons
          restartPolicy: Never
