apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-kotlin-spring
  namespace: demo
  labels:
    app: sample-kotlin-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-kotlin-spring
  template:
    metadata:
      labels:
        app: sample-kotlin-spring
    spec:
      containers:
        - name: sample-kotlin-spring # (1)
          image: quay.io/pminkows/sample-kotlin-spring:1.5.1.1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2 # (2)
              memory: "1Gi"
            requests:
              cpu: 0.1
              memory: "256Mi"
          resizePolicy: # (3)
            - resourceName: "cpu"
              restartPolicy: "NotRequired"
          readinessProbe: # (4)
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3