management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    metrics:
      enabled: false
    prometheus:
      enabled: true
